steps:

  # Deploy data ingestor
  - id: "deploy data ingestor function"
    name: "gcr.io/cloud-builders/gcloud"
    waitFor: ["-"]
    entrypoint: "bash"
    args:
      - -c
      - |
        gcloud functions deploy data-ingestor \
        --gen2 \
        --region europe-west1 \
        --runtime python311 \
        --source "./src/data_ingestor" \
        --entry-point "function_entry_point" \
        --trigger-http \
        --no-allow-unauthenticated \
        --memory 512MiB \
        --set-secrets /mnt2/secrets.env=crypto-gpt-env-secrets:8

  # Deploy bot
  - id: "deploy bot function"
    name: "gcr.io/cloud-builders/gcloud"
    waitFor: ["-"]
    entrypoint: "bash"
    args:
      - -c
      - |
        gcloud functions deploy bot \
        --gen2 \
        --region europe-west1 \
        --runtime python311 \
        --source "./src/bot" \
        --entry-point "function_entry_point" \
        --trigger-http \
        --no-allow-unauthenticated \
        --memory 1GiB \
        --set-secrets /mnt2/secrets.env=crypto-gpt-env-secrets:8 \
        --timeout 600
