# Generated by CodiumAI
from src.bot.util import format_value


import pytest


class TestFormatValue:

    # Returns a string with 5 significant figures for a valid float or integer input.
    def test_valid_input(self):
        input_val = 123.456789
        expected_output = "123.46"

        result = format_value(input_val)

        assert result == expected_output

    # Returns 'nan' for a float input with NaN value.
    def test_nan_input(self):
        input_val = float("nan")
        expected_output = "nan"

        result = format_value(input_val)

        assert result == expected_output

    # Returns a string with 5 significant figures for a valid string input that can be converted to a float.
    def test_valid_input(self):
        input_val = 123.456789
        expected_output = "123.46"

        result = format_value(input_val)

        assert result == expected_output

    # Returns the input value if it is not a valid float, integer or string input that can be converted to a float.
    def test_valid_input(self):
        input_val = 123.456789
        expected_output = "123.46"

        result = format_value(input_val)

        assert result == expected_output
